# Generated by Django 2.0.5 on 2018-05-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='chocie_text',
            new_name='choice_text',
        ),
    ]
